version: "3"
services:
  {{ cookiecutter.project_package_name }}:
    build: ./{{ cookiecutter.project_package_name }}
    depends_on:
      - database
    ports:
      - "{{ cookiecutter.api_port }}:{{ cookiecutter.api_port }}"
    volumes:
      - ./{{ cookiecutter.project_package_name }}/{{ cookiecutter.project_package_name }}:/code
  database:
    image: postgres
    expose:
      - "5432"
    env_file:
      - database/database.env
